### ISSUE TITLE
Specified column "FL_SECURITIZACAO_COB" is not in the row

### ISSUE THREAD

**Issue by lukaz-sampaio** [pjbank/pjbank-java-sdk#88]
Estou tentando gerar um boleto (`https://sandbox.pjbank.com.br/recebimentos/{{credencial}}/transacoes`), mas estou recebendo a seguinte _exception_: 

```log
br.com.pjbank.sdk.exceptions.PJBankException: Specified column "FL_SECURITIZACAO_COB" is not in the row
at br.com.pjbank.sdk.exceptions.PJBankExceptionHandler.handleFromJSONResponse(PJBankExceptionHandler.java:24)
at br.com.pjbank.sdk.api.PJBankClient.doRequest(PJBankClient.java:132)
at br.com.pjbank.sdk.recebimento.BoletosManager.create(BoletosManager.java:80)
```

Até mês passado estava funcionando. Acredito que mudaram alguma coisa lá no PJBank e não testaram ou talvez são apenas "maus dias".

Esse é a versão do SDK que estou usando:

```mvn
<dependency>
    <groupId>com.github.pjbank</groupId>
    <artifactId>pjbank-java-sdk</artifactId>
    <version>1b6b3e6433</version>
</dependency>
```

![image](https://user-images.githubusercontent.com/12944221/69678554-a8af2700-1084-11ea-9fa3-1366502456a9.png)

**Comment by lukaz-sampaio** [comment]
O problema era lá no webservice. Mandei um email para api@pjbank.com.br explicando a situação e o suporte prontamente me respondeu pedindo pra eu testar novamente pra confirmar a correção,
